# Environment setup

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
# !pip install imageio
# !pip install git+https://github.com/tensorflow/docs

In [ ]:
import tensorflow as tf
import glob
import imageio
import matplotlib.pyplot as plt
import numpy as np
import os
import PIL
import cv2
import pandas as pd

from PIL import Image, ImageOps
from tensorflow.keras import layers
import time
# import tensorflow_docs.vis.embed as embed
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from matplotlib.pyplot import imshow

from IPython import display

tf.config.run_functions_eagerly(False)

In [ ]:
# Use the GPU
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


# Define GAN Architecture

In [ ]:
def make_generator_model(noise_dim=40, data_dim=42):
    model = tf.keras.Sequential()
    model.add(layers.Dense(128, use_bias=False, input_shape=(noise_dim,)))
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    assert model.output_shape == (None, 128)  # Note: None is the batch size

    model.add(layers.Dense(64, use_bias=False))
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    assert model.output_shape == (None, 64)

    model.add(layers.Dense(32, use_bias=True))
    model.add(layers.Dropout(0.2))
    model.add(layers.LeakyReLU())

    assert model.output_shape == (None, 32)

    model.add(layers.Dense(data_dim-1, use_bias=False))
    # model.add(layers.LeakyReLU())

    assert model.output_shape == (None, data_dim - 1)

    # print(model.summary())

    return model

def make_discriminator_model(data_dim=42):  
    model = tf.keras.Sequential()
    model.add(layers.Dense(32, input_shape=(data_dim,)))
    model.add(layers.LeakyReLU())
    model.add(layers.Dropout(0.3))

    model.add(layers.Dense(16))
    model.add(layers.LeakyReLU())
    model.add(layers.Dropout(0.3))

    model.add(layers.Flatten())
    model.add(layers.Dense(1))

    return model


def discriminator_loss(real_output, fake_output, cross_entropy, d_loss):
    real_loss = cross_entropy(tf.ones_like(real_output), real_output)
    fake_loss = cross_entropy(tf.zeros_like(fake_output), fake_output)
    # d_loss.append(fake_loss)
    total_loss = real_loss + fake_loss
    return total_loss


def generator_loss(fake_output, cross_entropy):
    return cross_entropy(tf.ones_like(fake_output), fake_output)


# Notice the use of `tf.function`
# This annotation causes the function to be "compiled".
@tf.function
def train_step(images, generator_optimizer0, generator_optimizer1, discriminator_optimizer, cross_entropy, noise_dim, d_hist, g_hist, g_hist1, d_loss):
    noise = tf.random.normal([images.get_shape()[0], noise_dim], dtype=tf.dtypes.float64)
    # noise = tf.cast(tf.concat([noise, tf.round(tf.reshape(tf.gather(images, [images.get_shape()[1]-1], axis=1), [images.get_shape()[0], 1]))], 1), tf.dtypes.float64)

    # print(noise.shape)

    with tf.GradientTape() as gen_tape0, tf.GradientTape() as gen_tape1, tf.GradientTape() as disc_tape:
        generated_images0 = generator0(noise, training=False)
        # generated_images0 = tf.concat([tf.cast(generated_images0, tf.dtypes.float64) , tf.round(tf.reshape(tf.gather(images, [images.get_shape()[1]-1], axis=1), [images.get_shape()[0], 1]))], 1)
        generated_images1 = generator1(noise, training=False)
        generated_images0 = tf.concat([generated_images0, tf.zeros([images.get_shape()[0], 1])], 1)
        generated_images1 = tf.concat([generated_images1, tf.ones([images.get_shape()[0], 1])], 1)

        generated_images = tf.concat([generated_images0, generated_images1], 0)

        real_output = discriminator(images, training=True)
        fake_output = discriminator(generated_images, training=True)

        disc_loss = discriminator_loss(real_output, fake_output, cross_entropy, d_loss)

        generated_images0 = generator0(noise, training=True)
        generated_images1 = generator1(noise, training=True)
        generated_images0 = tf.concat([generated_images0, tf.zeros([images.get_shape()[0], 1])], 1)
        generated_images1 = tf.concat([generated_images1, tf.ones([images.get_shape()[0], 1])], 1)

        real_output = discriminator(images, training=False)
        fake_output0 = discriminator(generated_images0, training=False)
        fake_output1 = discriminator(generated_images1, training=False)

        gen_loss0 = generator_loss(fake_output0, cross_entropy)
        gen_loss1 = generator_loss(fake_output1, cross_entropy)

        # g_hist.append(gen_loss0.numpy())
        # g_hist1.append(gen_loss1.numpy())
        # d_hist.append(disc_loss.numpy())

    gradients_of_generator0 = gen_tape0.gradient(gen_loss0, generator0.trainable_variables)
    gradients_of_generator1 = gen_tape1.gradient(gen_loss1, generator1.trainable_variables)
    gradients_of_discriminator = disc_tape.gradient(disc_loss, discriminator.trainable_variables)

    generator_optimizer0.apply_gradients(zip(gradients_of_generator0, generator0.trainable_variables))
    generator_optimizer1.apply_gradients(zip(gradients_of_generator1, generator1.trainable_variables))
    discriminator_optimizer.apply_gradients(zip(gradients_of_discriminator, discriminator.trainable_variables))

def train(dataset, epochs, generator_optimizer0, generator_optimizer1, discriminator_optimizer, cross_entropy, noise_dim):
    # plt.figure()
    for epoch in range(epochs):
      start = time.time()

      d_hist, g_hist, g_hist1, d_loss = list(), list(), list(), list()
      for image_batch in dataset:
        train_step(image_batch, generator_optimizer0, generator_optimizer1, discriminator_optimizer, cross_entropy, noise_dim, d_hist, g_hist, g_hist1, d_loss)

      # d_hist = np.mean(d_hist)
      # g_hist = np.mean(g_hist)
      # g_hist1 = np.mean(g_hist1)
      # d_loss = np.mean(d_loss)
      # print(g_hist)
      # print(g_hist1)
      # print(d_hist)
      # print(d_loss)
      # plot_history(d_hist, g_hist, epoch)

      print ('Time for epoch {} is {} sec'.format(epoch + 1, time.time()-start))

def plot_history(d_hist, g_hist, x):
	# plot loss
	plt.plot(x, d_hist, label='d')
	plt.plot(x, g_hist, label='g')
	plt.legend()

# Data

In [ ]:
### DEFINE VARIABLES ###
global BUFFER_SIZE
global BATCH_SIZE
global EPOCHS

BUFFER_SIZE = 1100
BATCH_SIZE = 1024
EPOCHS = 1000

path_train = 'Train.csv'

In [ ]:
### LOAD DATA ###
X = pd.read_csv(path_train)
X

protocol_type  service  ...  dst_host_same_src_port_rate  attack
0                  1       29  ...                         0.00       1
1                  2       48  ...                         0.37       1
2                  2       12  ...                         0.01       0
3                  1        6  ...                         0.00       1
4                  1       24  ...                         0.00       0
...              ...      ...  ...                          ...     ...
92134              1       24  ...                         0.01       0
92135              1       24  ...                         0.00       0
92136              1       20  ...                         0.80       0
92137              1       24  ...                         0.14       0
92138              1       24  ...                         0.02       0

[92139 rows x 16 columns]

In [ ]:
### Categorical ranges ###
cat_columns = ["protocol_type", "service", "flag", "same_srv_rate", "diff_srv_rate", "logged_in"]
cat_codes = {}
for col in cat_columns:
  cat_codes[col] = X[col].unique()

df_X = X

In [ ]:
cat_codes

{'diff_srv_rate': array([2, 0, 1]),
 'flag': array([ 1,  9,  5,  2,  4,  3,  0,  7,  8, 10,  6]),
 'logged_in': array([0, 1]),
 'protocol_type': array([1, 2, 0]),
 'same_srv_rate': array([0, 2, 1]),
 'service': array([29, 48, 12,  6, 24, 34, 62, 14, 20, 11, 52, 35,  8, 15, 43, 58, 13,
        65, 36, 41,  5, 32, 17, 37, 30, 60, 53, 39, 18,  2, 57, 33, 16, 23,
        19, 28, 40,  7, 21, 56,  4, 46, 63, 10, 42, 31, 55, 49, 54,  9, 64,
        26, 51, 38, 50, 47, 45, 22, 61, 44, 27,  1, 25,  3,  0, 59])}

In [ ]:
### Add noise to categorical columns ###
noise = np.random.normal(0,0.1,(len(X),len(cat_columns)))
noise[noise > 0.2] = 0.2
noise[noise < -0.2] = -0.2
X[cat_columns] = X[cat_columns] + noise

# for col in cat_columns + []:
#   X[col] = X[col] / np.max(cat_codes[col])

df_X = X
df_X

protocol_type    service  ...  dst_host_same_src_port_rate  attack
0           0.804169  29.066497  ...                         0.00       1
1           1.800000  48.007992  ...                         0.37       1
2           1.988411  11.919183  ...                         0.01       0
3           0.929805   5.978107  ...                         0.00       1
4           1.080933  23.822888  ...                         0.00       0
...              ...        ...  ...                          ...     ...
92134       1.031245  23.921560  ...                         0.01       0
92135       1.086161  23.898786  ...                         0.00       0
92136       0.946292  19.835558  ...                         0.80       0
92137       0.955492  23.989873  ...                         0.14       0
92138       0.978967  24.200000  ...                         0.02       0

[92139 rows x 16 columns]

In [ ]:
### Vectorice to numpy ###
columns = X.columns
X = X.to_numpy()
X

array([[8.04169295e-01, 2.90664965e+01, 9.24939865e-01, ...,
        7.00000000e-02, 0.00000000e+00, 1.00000000e+00],
       [1.80000000e+00, 4.80079924e+01, 9.03848647e+00, ...,
        6.20000000e-01, 3.70000000e-01, 1.00000000e+00],
       [1.98841112e+00, 1.19191829e+01, 9.20000000e+00, ...,
        3.00000000e-02, 1.00000000e-02, 0.00000000e+00],
       ...,
       [9.46291930e-01, 1.98355576e+01, 8.99609523e+00, ...,
        3.00000000e-01, 8.00000000e-01, 0.00000000e+00],
       [9.55491792e-01, 2.39898732e+01, 9.12726732e+00, ...,
        0.00000000e+00, 1.40000000e-01, 0.00000000e+00],
       [9.78966933e-01, 2.42000000e+01, 8.95564465e+00, ...,
        0.00000000e+00, 2.00000000e-02, 0.00000000e+00]])

In [ ]:
### RESHAPE DATA ###
train_data = X.reshape(X.shape[0], X.shape[1])

In [ ]:
noise_dim = 8
data_dim = X.shape[1]
data_dim

16

# Build and Run

In [ ]:
# Batch and shuffle the data
train_dataset = tf.data.Dataset.from_tensor_slices(train_data).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)

generator0 = make_generator_model(noise_dim, data_dim)
generator1 = make_generator_model(noise_dim, data_dim)

# noise = tf.random.normal([1, noise_dim])
# noise = tf.concat([noise, tf.ones([1,1])], 1)
# generated_malware = generator(noise, training=False)
# generated_malware = tf.concat([generated_malware, tf.ones([1,1])], 1)

discriminator = make_discriminator_model(data_dim)
# decision = discriminator(generated_malware)
# print(decision)

# This method returns a helper function to compute cross entropy loss
cross_entropy = tf.keras.losses.BinaryCrossentropy(from_logits=True)

generator_optimizer0 = tf.keras.optimizers.Adam(learning_rate=0.001)
generator_optimizer1 = tf.keras.optimizers.Adam(learning_rate=0.001)
discriminator_optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

train(train_dataset, EPOCHS, generator_optimizer0, generator_optimizer1, discriminator_optimizer, cross_entropy, noise_dim)

Time for epoch 1 is 6.640403509140015 sec
Time for epoch 2 is 0.6644165515899658 sec
Time for epoch 3 is 0.6546406745910645 sec
Time for epoch 4 is 0.6138420104980469 sec
Time for epoch 5 is 0.6492741107940674 sec
Time for epoch 6 is 0.6179847717285156 sec
Time for epoch 7 is 0.6574780941009521 sec
Time for epoch 8 is 0.6471512317657471 sec
Time for epoch 9 is 0.6092479228973389 sec
Time for epoch 10 is 0.6359846591949463 sec
Time for epoch 11 is 0.6531720161437988 sec
Time for epoch 12 is 0.6507508754730225 sec
Time for epoch 13 is 1.2708446979522705 sec
Time for epoch 14 is 0.6069519519805908 sec
Time for epoch 15 is 0.6804418563842773 sec
Time for epoch 16 is 0.6177325248718262 sec
Time for epoch 17 is 0.615532636642456 sec
Time for epoch 18 is 0.629202127456665 sec
Time for epoch 19 is 0.6040501594543457 sec
Time for epoch 20 is 0.6001641750335693 sec
Time for epoch 21 is 0.6325931549072266 sec
Time for epoch 22 is 0.622492790222168 sec
Time for epoch 23 is 0.6326923370361328 sec
T

# Generate and Discriminate

In [ ]:
num_samples = 100000
num_samples_1 = int(num_samples/2)
num_samples_0 = int(num_samples - num_samples_1)

noise = tf.random.normal([num_samples_0, noise_dim])
labels = tf.concat([tf.ones([num_samples_1,1]), tf.zeros([num_samples_0,1])], 0)
# noise = tf.concat([noise, labels], 1)
# generated_malware = generator(noise, training=False)
generated_malware0 = generator0(noise, training=False)

noise = tf.random.normal([num_samples_1, noise_dim])
generated_malware1 = generator1(noise, training=False)

generated_malware = tf.concat([generated_malware1, generated_malware0], 0)
generated_malware = tf.concat([generated_malware, labels], 1)
generated_malware

<tf.Tensor: shape=(100000, 16), dtype=float32, numpy=
array([[-1.56389356e-01,  5.00511742e+00,  4.98795986e+00, ...,
        -2.15969354e-01,  5.72412670e-01,  1.00000000e+00],
       [ 1.39453709e+00,  7.22771454e+01,  6.41177082e+00, ...,
         6.01485521e-02, -7.91153789e-01,  1.00000000e+00],
       [ 7.33363092e-01,  4.15472870e+01,  4.00114298e+00, ...,
         1.29937306e-01, -9.68943723e-03,  1.00000000e+00],
       ...,
       [ 9.80542898e-01,  3.15154381e+01,  9.92795181e+00, ...,
         1.90067351e-01, -4.28379059e-01,  0.00000000e+00],
       [ 9.19324338e-01,  2.89860439e+01,  9.91329098e+00, ...,
         4.82860431e-02, -2.96291083e-01,  0.00000000e+00],
       [ 8.43213916e-01,  3.15436592e+01,  1.04393635e+01, ...,
        -2.53585409e-02, -2.99624443e-01,  0.00000000e+00]], dtype=float32)>

In [ ]:
decision = discriminator(generated_malware)
decision

<tf.Tensor: shape=(100000, 1), dtype=float32, numpy=
array([[ 0.17005745],
       [ 0.33248356],
       [ 0.17794168],
       ...,
       [-0.1603883 ],
       [-0.12531012],
       [-0.13347799]], dtype=float32)>

# Helper: Round Categorical

In [ ]:
def round_categorical(df_samples, cat_columns=[], cat_codes={}):
  # for col in cat_columns:
  #   df_samples[col] = df_samples[col] * (len(cat_codes[col].keys())-1) 

  # for col in cat_columns:
  #   df_samples[col] = df_samples[col] * np.max(cat_codes[col])
  
  df_samples[cat_columns] = np.around(df_samples[cat_columns])
  df_samples[df_samples[cat_columns] <= 0] = 0

  # If a value is bigger than the largest category code, map it to largest category code
  for col in cat_columns:
    largest_code_value = max(k for k in cat_codes[col])
    df_samples.loc[df_samples[col] > largest_code_value, col] = largest_code_value
    # df_samples[col] = df_samples[col] / (len(cat_codes[col].keys())-1)
  
  df_samples.loc[df_samples['dst_host_count'] <= 0, 'dst_host_count'] = 0
  df_samples.loc[df_samples['dst_host_count'] > 1, 'dst_host_count'] = 1

  df_samples['dst_host_same_srv_rate'] = np.around(df_samples['dst_host_same_srv_rate'], 2)
  df_samples.loc[df_samples['dst_host_same_srv_rate'] <= 0, 'dst_host_same_srv_rate'] = 0
  df_samples.loc[df_samples['dst_host_same_srv_rate'] > 1, 'dst_host_same_srv_rate'] = 1

  df_samples['dst_host_diff_srv_rate'] = np.around(df_samples['dst_host_diff_srv_rate'], 2)
  df_samples.loc[df_samples['dst_host_diff_srv_rate'] <= 0, 'dst_host_diff_srv_rate'] = 0
  df_samples.loc[df_samples['dst_host_diff_srv_rate'] > 1, 'dst_host_diff_srv_rate'] = 1

  df_samples['dst_host_same_src_port_rate'] = np.around(df_samples['dst_host_same_src_port_rate'], 2)
  df_samples.loc[df_samples['dst_host_same_src_port_rate'] <= 0, 'dst_host_same_src_port_rate'] = 0
  df_samples.loc[df_samples['dst_host_same_src_port_rate'] > 1, 'dst_host_same_src_port_rate'] = 1

  df_samples['dst_host_diff_srv_rate'] = np.around(df_samples['dst_host_diff_srv_rate'], 2)
  df_samples.loc[df_samples['dst_host_diff_srv_rate'] <= 0, 'dst_host_diff_srv_rate'] = 0
  df_samples.loc[df_samples['dst_host_diff_srv_rate'] > 1, 'dst_host_diff_srv_rate'] = 1

  return df_samples

In [ ]:
np_generated_malware = generated_malware.numpy()
df_generated_malware = pd.DataFrame(np_generated_malware, columns=columns)
df_generated_malware

protocol_type    service  ...  dst_host_same_src_port_rate  attack
0          -0.156389   5.005117  ...                     0.572413     1.0
1           1.394537  72.277145  ...                    -0.791154     1.0
2           0.733363  41.547287  ...                    -0.009689     1.0
3           0.672015  34.323189  ...                    -0.049139     1.0
4           0.415534  27.253134  ...                     0.152595     1.0
...              ...        ...  ...                          ...     ...
99995       0.988113  31.984766  ...                    -0.422227     0.0
99996       0.995580  30.617098  ...                    -0.377182     0.0
99997       0.980543  31.515438  ...                    -0.428379     0.0
99998       0.919324  28.986044  ...                    -0.296291     0.0
99999       0.843214  31.543659  ...                    -0.299624     0.0

[100000 rows x 16 columns]

In [ ]:
generated_malware_rounded = round_categorical(df_generated_malware, cat_columns, cat_codes=cat_codes)
generated_malware_rounded

protocol_type  service  ...  dst_host_same_src_port_rate  attack
0                0.0      5.0  ...                         0.57     1.0
1                1.0     65.0  ...                         0.00     1.0
2                1.0     42.0  ...                         0.00     1.0
3                1.0     34.0  ...                         0.00     1.0
4                0.0     27.0  ...                         0.15     1.0
...              ...      ...  ...                          ...     ...
99995            1.0     32.0  ...                         0.00     0.0
99996            1.0     31.0  ...                         0.00     0.0
99997            1.0     32.0  ...                         0.00     0.0
99998            1.0     29.0  ...                         0.00     0.0
99999            1.0     32.0  ...                         0.00     0.0

[100000 rows x 16 columns]

In [ ]:
decision = discriminator(generated_malware_rounded.to_numpy())
decision

<tf.Tensor: shape=(100000, 1), dtype=float32, numpy=
array([[ 0.11941531],
       [ 0.52604043],
       [ 0.20191905],
       ...,
       [-0.1387291 ],
       [-0.11991832],
       [-0.204688  ]], dtype=float32)>

In [ ]:
generated_malware_rounded.to_csv('generated.csv', index=False)